export const ACTION_TYPES = {
  INITIAL_REQUEST: 'INITIAL_REQUEST',
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  SET_LANGUAGE_SUCCESS: 'SET_LANGUAGE_SUCCESS'
};

export const BASE_URL = '';
export const LOGIN_URL = 'login';
